### ISSUE TITLE
Update releases.

### ISSUE THREAD

**Issue by nderlyn** [boyestrous/elite-vr-cockpit#11]
Howdy,

Would you be able to compile your changes and post a release? It seems like dantman hasn't made changes in a very very long time and his current release is broken with the current version of ED: Odyssey. I tried compiling yours myself, however for whatever reason the overlay controllers were offset by several meters and I have no clue what could be causing that, most likely I didn't build it properly. But it seemed to read the correct keybinds and everything else just fine. So I imagine it should work with update 15 as is.

Anyways, appreciate the work.

Thanks!

**Comment by boyestrous** [comment]
I'm going to post a release today, sorry for the delay!

**Comment by boyestrous** [comment]
@nderlyn Let me know if you have any trouble with this one!

https://github.com/boyestrous/elite-vr-cockpit/releases
