### ISSUE TITLE
In Debugging Process Directory shows .../Parker/... user folder 

### ISSUE THREAD

**Issue by obxBill** [boyestrous/elite-vr-cockpit#19]
See **Process Directory**
Assume the _Parker_ user folder is a static value based on dev client for the app?  The user folder should derive from the client itself where run.

![image](https://github.com/boyestrous/elite-vr-cockpit/assets/22101205/8fcf9d6a-ad28-4fef-90a5-1f1eced4a062)

**Comment by boyestrous** [comment]
Whelp - Looks like I forgot to connect the wiring on that panel. I'll get a fix pushed to a new release asap.

In the meantime, are you seeing any other messages that prevent you from using the app?
